language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
  fast_finish: true

before_script: 
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - phpenv config-add test/phpconfig.ini
  - composer install -n --prefer-source

script: vendor/bin/phpunit --coverage-clover coverage.clover