language: php
php:
  - 5.5
  - 5.4
  - hhvm

script: phpunit --configuration phpunit.xml ./test/ --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
