language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script: 
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - phpenv config-add test/phpconfig.ini

script: phpunit --configuration phpunit.xml --coverage-clover coverage.clover
